#!/usr/bin/env sh
# Define cores in your shell RC file

source ./envsetup
if [ -z "$1" ]
then
    make saber_defconfig -j6 -j$CORES
    make -j6 uImage -j$CORES
else
    make saber_defconfig -j$CORES
    make "$1"
fi
